version: '3'
services:

  api-bannayuu-calculate:
    image: api-bannayuu-calculate:1.0.0
    ports:
      - 36006:36006
    volumes:
      - ./volumes/log:/app/dist/logs
    restart: unless-stopped 
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=development
      - APP_PORT=36006
      - DB_HOST=192.168.81.135
      - DB_PORT=50005
      - DB_NAME=demo_bannayuu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=P@ssw0rd
      - URL_CALCULATE_MASTER=http://172.25.30.64:36007/api/v1/bannayuu/calculate/master/cal
      - JWT_TOKEN=f56c3775-07b0-45e7-800f-304274533cb7
    
    
      