version: '3'
services:

  api-bannayuu-calculate:
    image: api-bannayuu-calculate:1.0.0
    ports:
      - 4060:4060
    volumes:
      - ./volumes/log:/app/dist/logs
    restart: unless-stopped 
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=productiom
      - APP_PORT=4060
      - DB_HOST=local.uat.bannayuu.com
      - DB_PORT=5432
      - DB_NAME=cit_bannayuu_db
      - DB_USERNAME=cit
      - DB_PASSWORD=db13apr
      - URL_CALCULATE_MASTER=http://localhost:4095/api/v1/bannayuu/calculate/master/cal
      - JWT_TOKEN=f56c3775-07b0-45e7-800f-304274533cb7
    